// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ3AIoY9opvTF-IMZVJkSsfxrFJEKF89Q',
    appId: '1:603048605261:web:935ef81c1af01e14ed0e04',
    messagingSenderId: '603048605261',
    projectId: 'inventory-check-system',
    authDomain: 'inventory-check-system.firebaseapp.com',
    storageBucket: 'inventory-check-system.appspot.com',
    measurementId: 'G-HENK29GB2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhH2zd0kJb6qSPAoREhC2hF9QGIO8fn9Q',
    appId: '1:603048605261:android:13775c8b0866ad2aed0e04',
    messagingSenderId: '603048605261',
    projectId: 'inventory-check-system',
    storageBucket: 'inventory-check-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMA7C-iSV6o1jDahcGiRdBbYZBCikZ9KM',
    appId: '1:603048605261:ios:3e3cd18dbbfeeb8bed0e04',
    messagingSenderId: '603048605261',
    projectId: 'inventory-check-system',
    storageBucket: 'inventory-check-system.appspot.com',
    iosClientId: '603048605261-dpp4v98n3rs8gumolq390has043kdpn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMA7C-iSV6o1jDahcGiRdBbYZBCikZ9KM',
    appId: '1:603048605261:ios:3e3cd18dbbfeeb8bed0e04',
    messagingSenderId: '603048605261',
    projectId: 'inventory-check-system',
    storageBucket: 'inventory-check-system.appspot.com',
    iosClientId: '603048605261-dpp4v98n3rs8gumolq390has043kdpn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutterApp',
  );
}
